### ISSUE TITLE
invalid key

### ISSUE THREAD

**Issue by nolageek** [Du9L/vpsmon#1]
I keep getting invalid key - also, I notice that solusvm uses 'key' and 'id' - I assume hash = id in config?

**Comment by dujiulun** [comment]
The code is intended to call SolusVM's Client API. As shown in [here](https://documentation.solusvm.com/display/DOCS/PHP+Code+Examples) it uses "key" and "hash" for authentication.
I noticed in [Admin API](https://documentation.solusvm.com/display/DOCS/Examples) it uses "key" and "id". Are you using the Admin API?
